language: go

env:
  global:
    - GO111MODULE=on

go: 
  - 1.12.9

os:
  - linux
  - osx
  - windows

before_install:
  - go get -u -v github.com/songgao/water
  - go get -u -v github.com/gorilla/mux
  - go get -u -v github.com/golang-collections/go-datastructures/queue
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      go get -u -v github.com/vishvananda/netlink
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      make "$TRAVIS_OS_NAME"
    else
      go build -o ./resource/point.windows.x86_64 main/point_windows.go
    fi
