language: go

go: 
  - 1.12.9

os:
  - linux
  - osx
  - windows

before_install:
  - go get -u -v github.com/songgao/water
  - go get -u -v github.com/gorilla/mux
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      go get -u -v github.com/milosgajdos83/tenus
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      make "$TRAVIS_OS_NAME"
    else
      go build -o ./resource/point.windows.x86_64 main/point_windows.go
    fi
