language: go

go: 
  - 1.12.9

os:
  - linux
  - osx
  - windows

before_install:
  - go get -v github.com/golang/protobuf/proto
  - go get -v github.com/go-redis/redis
  - go get -v github.com/songgao/water
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      go get -v github.com/milosgajdos83/tenus
    fi

script:
  - make "$TRAVIS_OS_NAME"